// ──────────────────────────────────────────────
//  Hipermaxi · Mock Data (dev fixtures)
//  Replace with real API calls / Server Components
// ──────────────────────────────────────────────
import type { Product, ProductSection, Category } from "@/components/types/product";

// ─── Categories ───────────────────────────────

export const CATEGORIES: Category[] = [
  {
    id: "supermercado",
    label: "Supermercado",
    href: "/categoria/supermercado",
    icon: "🛒",
    color: "bg-blue-50",
    accentColor: "text-blue-600",
  },
  {
    id: "farmacia",
    label: "Farmacia",
    href: "/categoria/farmacia",
    icon: "💊",
    color: "bg-rose-50",
    accentColor: "text-rose-600",
  },
  {
    id: "panaderia",
    label: "Panadería",
    href: "/categoria/panaderia",
    icon: "🥐",
    color: "bg-amber-50",
    accentColor: "text-amber-600",
  },
  {
    id: "mascotas",
    label: "Mascotas",
    href: "/categoria/mascotas",
    icon: "🐾",
    color: "bg-purple-50",
    accentColor: "text-purple-600",
  },
  {
    id: "frutas",
    label: "Frutas y Verduras",
    href: "/categoria/frutas-verduras",
    icon: "🥦",
    color: "bg-emerald-50",
    accentColor: "text-emerald-600",
  },
  {
    id: "lacteos",
    label: "Lácteos",
    href: "/categoria/lacteos",
    icon: "🥛",
    color: "bg-sky-50",
    accentColor: "text-sky-600",
  },
  {
    id: "carnes",
    label: "Carnes y Aves",
    href: "/categoria/carnes",
    icon: "🥩",
    color: "bg-red-50",
    accentColor: "text-red-600",
  },
  {
    id: "limpieza",
    label: "Limpieza",
    href: "/categoria/limpieza",
    icon: "🧹",
    color: "bg-cyan-50",
    accentColor: "text-cyan-600",
  },
  {
    id: "bebidas",
    label: "Bebidas",
    href: "/categoria/bebidas",
    icon: "🥤",
    color: "bg-orange-50",
    accentColor: "text-orange-600",
  },
  {
    id: "congelados",
    label: "Congelados",
    href: "/categoria/congelados",
    icon: "❄️",
    color: "bg-indigo-50",
    accentColor: "text-indigo-600",
  },
];

// ─── Products ─────────────────────────────────

const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "p001",
    name: "Aceite de Girasol Fino",
    brand: "Fino",
    price: 18.9,
    originalPrice: 22.5,
    discountPercent: 16,
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop&q=80",
    imageAlt: "Botella de aceite de girasol Fino",
    category: "supermercado",
    unit: "l",
    inStock: true,
  },
  {
    id: "p002",
    name: "Leche Entera UHT",
    brand: "Pil Andina",
    price: 7.5,
    imageUrl: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop&q=80",
    imageAlt: "Caja de leche UHT Pil Andina",
    category: "lacteos",
    unit: "l",
    inStock: true,
    badge: "Nuevo",
    isNew: true,
  },
  {
    id: "p003",
    name: "Arroz Extra Calidad Superior",
    brand: "Bolívar",
    price: 12.9,
    originalPrice: 15.0,
    discountPercent: 14,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop&q=80",
    imageAlt: "Bolsa de arroz extra Bolívar",
    category: "supermercado",
    unit: "kg",
    inStock: true,
  },
  {
    id: "p004",
    name: "Yogur Griego Natural",
    brand: "Pil",
    price: 9.9,
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop&q=80",
    imageAlt: "Yogur griego natural Pil",
    category: "lacteos",
    unit: "kg",
    inStock: true,
    badge: "Fit & Light",
  },
  {
    id: "p005",
    name: "Pan Integral Artesanal",
    brand: "Panadería Hipermaxi",
    price: 5.5,
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop&q=80",
    imageAlt: "Pan integral artesanal",
    category: "panaderia",
    unit: "u",
    inStock: true,
    badge: "Fresco",
  },
  {
    id: "p006",
    name: "Detergente Líquido Ariel",
    brand: "Ariel",
    price: 34.9,
    originalPrice: 42.0,
    discountPercent: 17,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&q=80",
    imageAlt: "Detergente líquido Ariel",
    category: "limpieza",
    unit: "l",
    inStock: true,
  },
  {
    id: "p007",
    name: "Avena Quaker Tradicional",
    brand: "Quaker",
    price: 11.5,
    imageUrl: "https://images.unsplash.com/photo-1614961233913-a5113a4a34ed?w=400&h=400&fit=crop&q=80",
    imageAlt: "Avena Quaker tradicional",
    category: "supermercado",
    unit: "kg",
    inStock: true,
    badge: "Fit & Light",
  },
  {
    id: "p008",
    name: "Agua Mineral Sin Gas",
    brand: "Manantial",
    price: 4.5,
    originalPrice: 5.5,
    discountPercent: 18,
    imageUrl: "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400&h=400&fit=crop&q=80",
    imageAlt: "Botella de agua mineral sin gas Manantial",
    category: "bebidas",
    unit: "l",
    inStock: true,
  },
];

const FIT_LIGHT_PRODUCTS: Product[] = [
  {
    id: "fl001",
    name: "Granola Sin Azúcar",
    brand: "Natual",
    price: 22.9,
    imageUrl: "https://images.unsplash.com/photo-1517093602195-b40af9688f2a?w=400&h=400&fit=crop&q=80",
    imageAlt: "Granola sin azúcar Natual",
    category: "supermercado",
    unit: "g",
    inStock: true,
    badge: "Fit & Light",
  },
  {
    id: "fl002",
    name: "Leche Descremada UHT",
    brand: "Pil Andina",
    price: 7.9,
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop&q=80",
    imageAlt: "Leche descremada Pil Andina",
    category: "lacteos",
    unit: "l",
    inStock: true,
    badge: "Fit & Light",
  },
  {
    id: "fl003",
    name: "Atún en Agua Natural",
    brand: "Mar del Plata",
    price: 14.5,
    originalPrice: 17.0,
    discountPercent: 15,
    imageUrl: "https://images.unsplash.com/photo-1607623488888-73a1f1c90f4f?w=400&h=400&fit=crop&q=80",
    imageAlt: "Lata de atún en agua natural",
    category: "supermercado",
    unit: "g",
    inStock: true,
    badge: "Fit & Light",
  },
  {
    id: "fl004",
    name: "Barras de Cereal Integral",
    brand: "Nutrilac",
    price: 8.9,
    imageUrl: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=400&h=400&fit=crop&q=80",
    imageAlt: "Barras de cereal integral Nutrilac",
    category: "supermercado",
    unit: "u",
    inStock: true,
    badge: "Fit & Light",
    isNew: true,
  },
  {
    id: "fl005",
    name: "Aceite de Oliva Extra Virgen",
    brand: "Carbonell",
    price: 45.9,
    originalPrice: 54.0,
    discountPercent: 15,
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop&q=80",
    imageAlt: "Botella de aceite de oliva extra virgen",
    category: "supermercado",
    unit: "l",
    inStock: true,
    badge: "Fit & Light",
  },
  {
    id: "fl006",
    name: "Quinua Orgánica Real",
    brand: "Andean",
    price: 18.0,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop&q=80",
    imageAlt: "Quinua orgánica real boliviana",
    category: "supermercado",
    unit: "kg",
    inStock: true,
    badge: "Fit & Light",
    isNew: true,
  },
  {
    id: "fl007",
    name: "Bebida Vegetal de Almendra",
    brand: "Alpro",
    price: 24.5,
    imageUrl: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop&q=80",
    imageAlt: "Bebida vegetal de almendra Alpro",
    category: "bebidas",
    unit: "l",
    inStock: false,
    badge: "Fit & Light",
  },
  {
    id: "fl008",
    name: "Yogur Natural Sin Azúcar",
    brand: "Pil",
    price: 6.9,
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop&q=80",
    imageAlt: "Yogur natural sin azúcar Pil",
    category: "lacteos",
    unit: "g",
    inStock: true,
    badge: "Fit & Light",
  },
];

// ─── Sections ─────────────────────────────────

export const PRODUCT_SECTIONS: ProductSection[] = [
  {
    id: "mas-vendidos",
    title: "Los más vendidos en Cochabamba",
    subtitle: "Lo que eligen nuestros clientes esta semana",
    products: SAMPLE_PRODUCTS,
    viewAllHref: "/mas-vendidos",
  },
  {
    id: "fit-light",
    title: "Fit & Light",
    subtitle: "Opciones saludables para tu estilo de vida",
    products: FIT_LIGHT_PRODUCTS,
    viewAllHref: "/fit-light",
  },
];
